### ISSUE TITLE
small tokenization issue

### ISSUE THREAD

**Issue by c-cube** [rgrinberg/oasis.vim#1]
library names can contain numbers :-)
![2016-11-02-101845_443x43_scrot](https://cloud.githubusercontent.com/assets/1274291/19923037/c1d3e73c-a0e5-11e6-9d3a-6a7a1c6ae42b.png)

**Comment by rgrinberg** [comment]
Is this a problem with https://github.com/rgrinberg/vim-ocaml/blob/master/syntax/oasis.vim as well?

I should probably mention that this repo has been subsumed by vim-ocaml

**Comment by c-cube** [comment]
Riiight, my bad, I'm actually using vim-ocaml, so I'll move the issue there.

**Comment by c-cube** [comment]
moved to https://github.com/rgrinberg/vim-ocaml/issues/13
